# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Terracoin
  fr: Terracoin
  fi: Terracoin

email: support@terracoin.io

description:
  en: Terracoin is a secure, innovative, flexible, and easy cryptocurrency.
  fr: Terracoin est une crypto-monnaie sécurisée, innovante, flexible et facile.
  fi: Terracoin on turvallinen, innovatiivinen, joustava ja helppo kryptovaluutta.

copyright:
  en: Copyright &copy; 2018 <a href="https://terracoin.io/">Terracoin</a>
  fr: Droits d'auteur &copy; 2018 <a href="https://terracoin.io/">Terracoin</a>
  fi: Tekijänoikeudet &copy; 2018 <a href="https://terracoin.io/">Terracoin</a>

index:
  en: /index.html
  fr: /accueil.html
  fi: /indeksi.html

feed:
  en: /feed.xml
  fr: /flux.xml
  fi: /syotto.xml

top:
  en: Top
  fr: Haut
  fi: Ylin

language:
  en: Language
  fr: Langage
  fi: Kieli

langs:
  en: English
  fr: Français
  fi: Suomi

newsletter_form_subscribe:
  en: Subscribe
  fr: Souscrire
  fi: Tilaa

newsletter_form_email:
  en: your email
  fr: votre email
  fi: sähköpostisi

newsletter_form_enroll:
  en: Enroll
  fr: Inscrire
  fi: Osallistu

scrolldown:
  en: Scroll down
  fr: Défiler vers le bas
  fi: Rullaa alas

newsletter_blurb:
  en: Follow us on social media and subscribe to our newsletter for great crypto content.
  fr:
  fi:

baseurl: ""
trcver: 0.12.1

url: "https://terracoin.io"

twitter_username: jekyllrb

github_username:  jekyll

# Build settings
markdown: kramdown
