# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Terracoin
  fr: Terracoin
  fi: Terracoin
  pt: Terracoin
  nl: Terracoin

email: support@terracoin.io

description:
  en: Terracoin is a secure, innovative, flexible, and easy cryptocurrency.
  fr: Terracoin est une crypto-monnaie sécurisée, innovante, flexible et facile.
  fi: Terracoin on turvallinen, innovatiivinen, joustava ja helppo kryptovaluutta.
  pt: Terracoin é uma criptomoeda segura, inovadora, flexível e simples.
  nl: Terracoin is een veilige, innovatieve, flexibele en eenvoudige cryptovaluta.

copyright:
  en: Copyright &copy; 2018 Terracoin
  fr: Droits d'auteur &copy; 2018 Terracoin
  fi: Tekijänoikeudet &copy; 2018 Terracoin
  pt: Copyright &copy; 2018 Terracoin. Todos os direitos reservados.
  nl: Auteursrechten &copy; 2018 Terracoin

disclaimer:
  en: <a href="/disclaimer/"><p>Disclaimer</p></a>
  fr: <a href="/disclaimer/"><p>Disclaimer</p></a>
  fi: <a href="/disclaimer/"><p>Disclaimer</p></a>
  pt: <a href="/aviso-legal/"><p>Aviso Legal</p></a>
  nl: <a href="/disclaimer-nl/"><p>Disclaimer</p></a>

index:
  en: /index.html
  fr: /accueil.html
  fi: /indeksi.html
  pt: /inicio.html
  nl: /startpagina.html

feed:
  en: /feed.xml
  fr: /flux.xml
  fi: /syotto.xml
  pt: /feed-pt.xml
  nl: /feed-nl.xml

top:
  en: Top
  fr: Haut
  fi: Ylin
  pt: Topo
  nl: Omhoog

language:
  en: Language
  fr: Langage
  fi: Kieli
  pt: Idioma
  nl: Taal

langs:
  en: English
  fr: Français
  fi: Suomi
  pt: Português
  nl: Nederlands

newsletter_form_subscribe:
  en: Subscribe
  fr: Souscrire
  fi: Tilaa
  pt: Subscrever
  nl: Abonneren 

newsletter_form_email:
  en: your email
  fr: votre email
  fi: sähköpostisi
  pt: o seu email
  nl: uw email

newsletter:
  en: Newsletter
  fr: Bulletin
  fi: Tiedote
  pt: Boletim de Notícias
  nl: Nieuwsbrief

chat:
  en: Questions?
  fr: Questions?
  fi: Kysymyksiä?
  pt: Questões?
  nl: Vragen?

news:
  en: News
  fr: Nouvelles
  fi: Uutiset
  pt: Noticias
  nl: Nieuws

newsletter_blurb:
  en: Follow us on social media and subscribe to our newsletter for great crypto content.
  fr: Suivez-nous sur les réseaux sociaux et abonnez-vous à notre newsletter pour un contenu crypto génial.
  fi: Seuraa meitä sosiaalisessa mediassa ja tilaa uutiskirjeemme hyvää krypto-sisältöä varten.
  pt: Siga-nos nas redes sociais e subscreva o nosso Boletim de Notícias para um cripto conteúdo fantástico.
  nl: Volg ons op sociale media en abonneer op onze nieuwsbrief voor geweldige crypto-content.

baseurl: ""
trcver: 0.12.1.8
trcverbin: 0.12.1

url: "https://terracoin.io"

twitter_username: jekyllrb

github_username:  jekyll

# Build settings
markdown: kramdown
